### ISSUE TITLE
can you share data pls

### ISSUE THREAD

**Issue by Sandy4321** [naveenkambham/BigFive-Personality-MachineLearning#1]
can you share data pls

**Comment by naveenkambham** [comment]
sorry, it was my master's thesis and many legalities are there around the data

**Comment by zubairahmedanas** [comment]
Could you please share sample data?
And also the workflow diagram

**Comment by naveenkambham** [comment]
Sorry, I don't have access to the data. Please contact kstanley@cs.usask.ca for any collaborations . See the following paper for workflow diagram. 
https://ieeexplore.ieee.org/abstract/document/8614854
